LECTURE = {
    "number": 1,
    "title": "Introduction to HCI",
    "subtitle": "Introduction to Human–Computer Interaction",
    "next": "Human Factors & Cognitive Foundations of HCI",
    "sections": [
        {"title": "What is HCI?", "blocks": [
            {"type": "text", "text": "**Human–Computer Interaction (HCI)** is the field concerned with how people interact with computing systems and how those systems are designed for human use."},
            {"type": "cards", "title": "🧑‍💻 Human + Interaction + Computer", "items": [
                ("Human", "People bring goals, knowledge, perception, memory, attention, and physical abilities to an interaction."),
                ("Interaction", "The exchange between a person and a computing system through actions, responses, and feedback."),
                ("Computer", "The system receives input, processes it, and produces information, feedback, or an action."),
            ]},
            {"type": "callout", "kind": "warning", "text": "💡 **Core Takeaway:** HCI studies the complete relationship, not just the screen."},
            {"type": "heading", "text": "The Three Core Elements"},
            {"type": "cards", "items": [
                ("1. Human", "Goals, perception, memory, attention, knowledge, motor abilities."),
                ("2. Interaction", "Input, dialogue, feedback, errors, communication, task completion."),
                ("3. Computer", "Hardware, software, data, processing, output, response."),
            ]},
            {"type": "callout", "text": "Good HCI considers all three together rather than optimizing only the technology."},
        ]},
        {"title": "Why HCI Matters & Its Scope", "blocks": [
            {"type": "steps", "title": "Why does HCI matter?", "items": [
                ("Technology is not enough", "A system can be technically correct and still be difficult to understand, inefficient to operate, or frustrating to use."),
                ("People have limitations", "Users have limited attention, memory, and perception. HCI helps designers account for these human characteristics."),
                ("Errors have consequences", "Poor interaction can lead to mistakes, wasted time, lost information, or unsafe actions, especially in critical systems."),
            ]},
            {"type": "callout", "kind": "success", "text": "HCI aims to make interaction understandable, effective, efficient, safe, and satisfying."},
            {"type": "cards", "title": "🔭 The Scope of HCI", "items": [
                ("Human factors", "Studies human abilities and limitations that influence interaction."),
                ("Interaction design", "Structures how users perform actions and how systems respond."),
                ("User interface design", "Creates the visible and interactive parts through which users communicate with systems."),
                ("Usability", "Examines whether users can accomplish tasks effectively, efficiently, and satisfactorily."),
                ("Accessibility", "Considers how people with different abilities can perceive and operate systems."),
                ("Evaluation", "Uses methods such as usability testing and expert inspection to identify problems."),
            ]},
        ]},
        {"title": "HCI vs GUI vs UI vs UX", "blocks": [
            {"type": "text", "text": "A GUI is an interface style; HCI is the broader discipline that studies interaction."},
            {"type": "tabs", "items": [
                ("GUI", "Windows, menus, buttons, icons, and visual controls form a graphical user interface. GUI answers: \"What does the interface look like?\""),
                ("UI / UX", "UI focuses on interface design; UX considers the broader experience users have while achieving their goals."),
                ("HCI", "HCI also studies human behavior, interaction, usability, accessibility, evaluation, and the context of use."),
            ]},
            {"type": "callout", "text": "**Therefore:** HCI includes interface design, but it is not limited to interface appearance."},
            {"type": "heading", "text": "HCI vs UI vs UX"},
            {"type": "cards", "items": [
                ("HCI", "A broad academic and professional field covering human factors, interaction, interface design, usability, accessibility, evaluation, and context."),
                ("UI", "The set of visible and interactive elements through which users communicate with a system."),
                ("UX", "The broader experience and perceptions users have before, during, and after interacting with a product or service."),
            ]},
            {"type": "callout", "kind": "warning", "text": "These concepts overlap, but they are not interchangeable terms."},
        ]},
        {"title": "The Interaction Cycle", "blocks": [
            {"type": "steps", "title": "🔁 What happens during an interaction?", "items": [
                ("Goal", "The user has an objective, such as sending a message or finding a record."),
                ("Action", "The user chooses an action through a keyboard, mouse, touch, voice, or another input method."),
                ("System response", "The computer processes the action and changes its state or produces information."),
                ("Feedback", "The system communicates what happened so the user can interpret the result and continue."),
            ]},
            {"type": "callout", "text": "Interaction is a continuous cycle of **goal → action → system response → feedback**."},
            {"type": "heading", "text": "🏧 Example: ATM Interaction"},
            {"type": "reveal", "label": "Show details", "items": [
                ("1. User", "Inserts card and enters a PIN.", "The user must recognize what information is requested and what action is expected."),
                ("2. Interface", "Displays menus and transaction options.", "Labels, grouping, and feedback guide the user through the task."),
                ("3. System", "Validates the PIN and processes the selected transaction.", "The system must respond predictably."),
                ("4. Feedback", "Shows status, asks for confirmation, and provides cash or an error message.", "Feedback tells the user what happened."),
            ]},
            {"type": "callout", "kind": "success", "text": "HCI evaluates whether this whole sequence is clear, efficient, safe, and recoverable."},
        ]},
        {"title": "Goals & Usability", "blocks": [
            {"type": "cards", "title": "🎯 Goals of a Good Interactive System", "items": [
                ("Effective", "Users can achieve the intended goal accurately and completely."),
                ("Efficient", "Users can complete tasks without unnecessary time or effort."),
                ("Learnable", "A new user can understand the basic interaction with reasonable effort."),
                ("Memorable", "A returning user can remember how to perform familiar tasks."),
                ("Safe", "The system prevents errors where possible and supports recovery when they occur."),
                ("Satisfying", "The interaction feels understandable, appropriate, and acceptable to the user."),
            ]},
            {"type": "heading", "text": "Usability: A Central HCI Concept"},
            {"type": "text", "text": "Usability asks whether specified users can achieve specified goals effectively, efficiently, and satisfactorily in a given context."},
            {"type": "tabs", "items": [
                ("Effectiveness", "Can the user actually complete the intended task and obtain the correct result?"),
                ("Efficiency", "How much time, effort, and unnecessary interaction are required to complete the task?"),
                ("Satisfaction", "Does the user find the interaction acceptable, understandable, and comfortable?"),
            ]},
            {"type": "callout", "text": "**Example:** A university LMS may have many features, but poor usability if students cannot easily find and submit an assignment."},
        ]},
        {"title": "The Human Side & Interaction Styles", "blocks": [
            {"type": "cards", "title": "🧠 HCI and the Human Side of Computing", "items": [
                ("Perception", "How users see, hear, and interpret information presented by the system."),
                ("Attention", "How users focus on relevant information while ignoring distractions."),
                ("Memory", "How short-term and long-term memory affect learning and remembering interactions."),
                ("Decision making", "How users select actions based on goals, information, and expectations."),
                ("Motor skills", "How physical abilities influence pointing, typing, touching, and other actions."),
                ("Mental models", "How users think a system works, and how those expectations affect their actions."),
            ]},
            {"type": "cards", "title": "🖱️ Common Interaction Styles", "items": [
                ("Command line", "Users type commands using a defined syntax. Powerful and efficient for experienced users."),
                ("Menus", "Users choose from visible options, reducing the need to remember commands."),
                ("Direct manipulation", "Users interact with visible objects, such as dragging a file or resizing a window."),
                ("Forms", "Users enter structured information into fields, such as registration or checkout forms."),
                ("Natural language", "Users communicate using everyday language through text or voice."),
                ("Touch & gestures", "Users interact through taps, swipes, pinches, and other physical gestures."),
            ]},
        ]},
        {"title": "Applications & Design Principles", "blocks": [
            {"type": "cards", "title": "🌍 HCI in Everyday Life", "items": [
                ("Smartphones", "Touch, gestures, notifications, and visual feedback support many different tasks."),
                ("Websites", "Navigation, forms, search, and information structure determine how easily users find content."),
                ("Banking", "Security, confirmation, error prevention, and transaction feedback are critical."),
                ("Healthcare", "Interfaces must present complex information clearly while supporting safe decisions."),
                ("Industrial systems", "Operators monitor equipment and respond to alarms; interaction must be predictable."),
                ("Games & VR", "Interaction, feedback, and immersive graphics combine to create an engaging experience."),
            ]},
            {"type": "cards", "title": "💼 Where HCI Is Used", "items": [
                ("Software development", "Developers use HCI principles to build interfaces that users can understand and operate effectively."),
                ("UX / UI design", "Designers use user research, interaction principles, and evaluation to improve products."),
                ("Data visualization", "HCI helps determine how information should be presented so users can interpret it correctly."),
                ("AI systems", "Intelligent systems still need understandable interaction, feedback, explanations, and user control."),
                ("Industrial systems", "Operators depend on clear displays, alarms, and safe interaction with complex equipment."),
                ("Research", "HCI supports studies of people, interfaces, accessibility, usability, and emerging interaction technologies."),
            ]},
            {"type": "cards", "title": "📐 Design Principles: First Look", "items": [
                ("Visibility", "Important information and available actions should be easy for users to notice."),
                ("Feedback", "The system should communicate the result of an action so users know what happened."),
                ("Consistency", "Similar actions and elements should behave and appear in similar ways."),
                ("Affordance", "The appearance of an element should suggest how it can be used."),
                ("Error prevention", "The design should reduce the likelihood of mistakes before they happen."),
                ("User control", "Users should be able to initiate, cancel, undo, or recover from actions where appropriate."),
            ]},
            {"type": "callout", "text": "These principles are covered in depth in Lecture 02."},
        ]},
        {"title": "Discussion & Summary", "is_last": True, "blocks": [
            {"type": "heading", "text": "Class Discussion"},
            {"type": "discussion", "items": [
                ("Is a beautiful interface necessarily usable?", "Give one example and explain why."),
                ("Can a technically powerful system have poor HCI?", "What makes the interaction difficult?"),
                ("What is the difference between HCI and GUI?", "Explain it in your own words."),
                ("Identify one HCI system you use every day.", "What is one thing it does well and one thing it could improve?"),
            ]},
            {"type": "answer_box", "label": "Your notes (for discussion only, not saved):"},
            {"type": "heading", "text": "Lecture Summary"},
            {"type": "callout", "text": "* HCI is about **people + interaction + computing**.\n* It goes beyond GUI design to include human factors, usability, accessibility, and evaluation.\n* Good HCI helps users understand systems, accomplish goals, and recover from errors."},
        ]},
    ],
}
